<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>72d56037-3933-4f67-9ffa-533526da55b8</elementGuidId>
    <imagePath></imagePath>
    <name>p_practiceFormInteractions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/main[1]/div[1]/p[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="px-4\ py-6\ sm\:px-0"] &gt; [class="mb-6"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>p</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Page_iframes/iframe_educenter</value>
        <webElementGuid>b63e86f2-20aa-4466-8c50-5e72c93396e9</webElementGuid>
    </webElementProperties>
</WebElementEntity>