<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f36493ec-1ff2-4809-8461-0cc61156ad3e</elementGuidId>
    <imagePath></imagePath>
    <name>span_priceQuantity</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ag-header-cell\ ag-header-cell-sortable\ ag-header-cell-auto-height\ ag-focus-managed\ ag-header-active"] [class="ag-header-cell-text"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[2]/div[1]/ti-selection-tool-wrapper[1]/ti-selection-parametric-table[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/span[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ag-header-cell-text') and equals(@text,'Price|Quantity (USD)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(2) &gt; .ag-header-cell-comp-wrapper &gt; .ag-cell-label-container &gt; .ag-header-cell-label &gt; .ag-header-cell-text</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ag-header-cell-text</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Price|Quantity (USD)</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>