<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d3408507-8a2c-4ab2-a4b1-549fe5e43e34</elementGuidId>
    <imagePath></imagePath>
    <name>button_batteryManagementIcs</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(3) &gt; [class="ti_p-dropdownMenu-button"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[3]/div[1]/div[1]/div[2]/ti-ai-recommendations-card[1]/div[1]/div[2]/div[1]/div[2]/ti-dropdown-panel[1]/div[2]/ul[1]/li[3]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ti_p-dropdownMenu-button') and equals(@text,'Battery management ICs')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Battery management ICs\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ti_p-dropdownMenu-button</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Battery management ICs</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>