<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>038f05e7-cdd1-465d-bfdb-3a340d817188</elementGuidId>
    <imagePath></imagePath>
    <name>div_close</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>svg</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//div/*[name()='svg'][1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-media-gallery &gt;&gt; internal:label=\"Close\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_product/tiSvgIcon_close</value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
</WebElementEntity>