<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1f02fbd8-b750-44a0-adb3-f7d214f432d4</elementGuidId>
    <imagePath></imagePath>
    <name>div_more</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ti_p-dropdownMenu\ hydrated"] &gt; div:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[3]/div[1]/div[1]/div[2]/ti-ai-recommendations-card[1]/div[1]/div[2]/div[1]/div[2]/ti-dropdown-panel[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'More')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-ai-recommendations-card ti-dropdown-panel div &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>More</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>