<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3e8a4295-87d9-470c-bfab-d85f5dc2d0ae</elementGuidId>
    <imagePath></imagePath>
    <name>link_download3</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="asset-item-MD-ozf76850uq"] &gt; .mod-row-space-phone a</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[6]/div[2]/div[1]/div[1]/ti-tab-container[1]/ti-tab-panel[3]/div[1]/div[1]/article[1]/div[1]/div[3]/ti-button[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/tool/download/TPS2X7XX-SCHEMATIC-CHECKLIST') and equals(@text,'Download')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#asset-item-MD-ozf76850uq &gt; div:nth-child(3) &gt; .u-fullWidth &gt; a</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/tool/download/TPS2X7XX-SCHEMATIC-CHECKLIST</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Download</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>