<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4081359b-6641-49b4-aa86-9d96dd2339d2</elementGuidId>
    <imagePath></imagePath>
    <name>span_productIdentifier</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(7) &gt; div:nth-of-type(1) [class="ag-cell-value"] &gt; span</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[4]/div[1]/ti-compare-gpns-table[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[4]/div[1]/div[1]/div[2]/div[1]/div[1]/div[7]/div[1]/div[1]/span[1]/span[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'DFP, UFP')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.ag-center-cols-container &gt; div:nth-child(7) &gt; div &gt; .ag-cell-wrapper &gt; .ag-cell-value &gt; span &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>DFP, UFP</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>