<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>963642bd-2720-4f93-b7f7-fb2d31df5ffc</elementGuidId>
    <imagePath></imagePath>
    <name>tiDialog_lm5066H1</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>ti-dialog</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//ti-dialog</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'hydrated') and equals(@text,'LM5066H1 Simplified Schematic')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-media-gallery ti-dialog</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>hydrated</value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>LM5066H1 Simplified Schematic</value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_product/tiMediaGallery_object</value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
</WebElementEntity>