<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5e742599-326f-475d-9fe9-16b338762f56</elementGuidId>
    <imagePath></imagePath>
    <name>tiSvgIcon_close</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ti-svg-icon-tertiary\ ti-svg-icon-size-s\ hydrated"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//dialog/div[1]/button[1]/ti-svg-icon[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ti-svg-icon-tertiary ti-svg-icon-size-s hydrated') and equals(@text,'')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-media-gallery &gt;&gt; internal:label=\"Close\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ti-svg-icon-tertiary ti-svg-icon-size-s hydrated</value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value></value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_product/tiDialog_lm5066H1</value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
</WebElementEntity>