<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>74a48ddb-6b44-4b44-85ce-e82757ce0ee7</elementGuidId>
    <imagePath></imagePath>
    <name>tiSvgIcon_recommendations</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ti-button-has-icon\ ti-button-link\ hydrated"] &gt; [class="ti-svg-icon-tertiary\ ti-svg-icon-size-m\ hydrated"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[3]/div[1]/div[1]/div[2]/ti-ai-recommendations-card[1]/div[1]/div[2]/div[2]/div[1]/div[2]/ti-button[2]/ti-svg-icon[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ti-svg-icon-tertiary ti-svg-icon-size-m hydrated') and equals(@text,'')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>ti-ai-recommendations-card ti-svg-icon &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ti-svg-icon-tertiary ti-svg-icon-size-m hydrated</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value></value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>