<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6f347e24-6fc7-4362-9023-86dfefb347ca</elementGuidId>
    <imagePath></imagePath>
    <name>div_sectionIntroduction</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="responsivegrid\ aem-GridColumn\ aem-GridColumn--default--12"] .sectionIntroduction</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'sectionIntroduction aem-GridColumn aem-GridColumn--default--12') and equals(@text,'Suchoptionen für Ihren Standort
            
            Suchen Sie geschätzte Versandkosten, Zahlungsoptionen und Steuerdetails, indem Sie unten Ihr Zielland eingeben.
            
             ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.sectionIntroduction &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>sectionIntroduction aem-GridColumn aem-GridColumn--default--12</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Suchoptionen für Ihren Standort
        
        Suchen Sie geschätzte Versandkosten, Zahlungsoptionen und Steuerdetails, indem Sie unten Ihr Zielland eingeben.
        
         </value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>