<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1e03cc10-e46a-4fd1-a374-38544c4181eb</elementGuidId>
    <imagePath></imagePath>
    <name>div_qualityReliabilityPackaging</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="u-flex-item\ mod-basis-100"] &gt; [class="ti_p-row"] &gt; [class="ti_p-col"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/article[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ti_p-col') and equals(@text,'Quality, reliability &amp; packaging data download
            SN74LVC1G17DBVTG4 
            
            By using this tool to “search” or “download”, you agree to TI’s terms of use, privacy policy (including cookie policy), and important notice.
            
            ...[truncated lines=405]')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.u-flex-item &gt; div &gt; div</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ti_p-col</value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Quality, reliability &amp; packaging data download
        SN74LVC1G17DBVTG4 
        
        By using this tool to “search” or “download”, you agree to TI’s terms of use, privacy policy (including cookie policy), and important notice.
        
        ...[truncated lines=405]</value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
</WebElementEntity>