<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f65c9327-aae7-477a-885b-6033094f7a3e</elementGuidId>
    <imagePath></imagePath>
    <name>label_assemblySite</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ti_p-col-3"] &gt; div &gt; .form-label</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/article[1]/div[1]/div[1]/section[2]/div[1]/div[2]/div[1]/label[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'form-label') and equals(@text,'Assembly site')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>label &gt;&gt; internal:text=\"Assembly site\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>form-label</value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Assembly site</value>
        <webElementGuid>0a9dae46-2b57-44ff-8e34-4181f7ed5e70</webElementGuid>
    </webElementProperties>
</WebElementEntity>