<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>22f60b2f-eed9-4962-85dc-8a6834040aa1</elementGuidId>
    <imagePath></imagePath>
    <name>link_hrPayrollForms</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[1]/div[11]/div[1]/div[1]/ul[1]/li[8]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="__tile421"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'__tile421') and equals(@title,'HR/Payroll Forms &amp; Cost Redistributions') and equals(@href,'{{url}}') and equals(@text,'HR/Payroll Forms &amp; Cost Redistributions')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"HR/Payroll Forms &amp; Cost Redistributions Navigation Tile\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>519f7259-8a78-4d49-9ece-2ee5b98f295e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>__tile421</value>
        <webElementGuid>519f7259-8a78-4d49-9ece-2ee5b98f295e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>HR/Payroll Forms &amp; Cost Redistributions</value>
        <webElementGuid>519f7259-8a78-4d49-9ece-2ee5b98f295e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>HR/Payroll Forms &amp; Cost Redistributions</value>
        <webElementGuid>519f7259-8a78-4d49-9ece-2ee5b98f295e</webElementGuid>
    </webElementProperties>
</WebElementEntity>