<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dab8ac69-0a94-446d-bd93-e62d61641351</elementGuidId>
    <imagePath></imagePath>
    <name>link_viewDesign</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>body:nth-of-type(1) &gt; container:nth-of-type(1) &gt; div:nth-of-type(5) &gt; bottom:nth-of-type(1) &gt; table:nth-of-type(1) &gt; tbody:nth-of-type(1) &gt; tr:nth-of-type(1) &gt; td:nth-of-type(2) &gt; results:nth-of-type(1) &gt; div:nth-of-type(1) &gt; table:nth-of-type(1) &gt; tbody:nth-of-type(3) &gt; tr:nth-of-type(2) &gt; td:nth-of-type(1) &gt; row-detail:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; a:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/container[1]/div[5]/bottom[1]/table[1]/tbody[1]/tr[1]/td[2]/results[1]/div[1]/table[1]/tbody[3]/tr[2]/td[1]/row-detail[1]/div[1]/div[2]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'results-row-details-view-design') and equals(@href,'/tool/TIDA-050077') and equals(@text,'View design')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>tbody:nth-child(4) &gt; .row-expand &gt; .results-table-row-details &gt; row-detail &gt; .results-row-details &gt; .results-row-details-info &gt; .results-row-details-info-top &gt; .results-row-details-description &gt; .results-row-details-view-design</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>results-row-details-view-design</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/tool/TIDA-050077</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>View design</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>