<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8ab8cd5c-4393-40cc-a90c-f4a26d135415</elementGuidId>
    <imagePath></imagePath>
    <name>raw_powerArchitecture</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="myrow15"] &gt; td &gt; raw</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/container[1]/div[5]/bottom[1]/table[1]/tbody[1]/tr[1]/td[2]/results[1]/div[1]/table[1]/tbody[16]/tr[1]/td[1]/raw[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Non-isolated power architecture with diagnostics reference design for protection relay modules')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#myrow15 raw &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Non-isolated power architecture with diagnostics reference design for protection relay modules</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>