<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fb104db4-538a-4fc8-911d-1aaf59fa2195</elementGuidId>
    <imagePath></imagePath>
    <name>td_referenceDesign</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="myrow0"] &gt; td:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/container[1]/div[5]/bottom[1]/table[1]/tbody[1]/tr[1]/td[2]/results[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'TIDA-020094 - NEW - 48V zone reference design')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#myrow0 &gt; td &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>TIDA-020094 - NEW - 48V zone reference design</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>