<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>be2ed61b-5f9e-4d6e-8eef-109fbd99dd90</elementGuidId>
    <imagePath></imagePath>
    <name>td_referenceDesign2</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="myrow2"] &gt; td:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/container[1]/div[5]/bottom[1]/table[1]/tbody[1]/tr[1]/td[2]/results[1]/div[1]/table[1]/tbody[3]/tr[1]/td[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'TIDA-050077.1 - NEW - 4kW, 12V input power path protection reference design using stackable eFuse')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#myrow2 &gt; td &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>TIDA-050077.1 - NEW - 4kW, 12V input power path protection reference design using stackable eFuse</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>