<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2226db6e-c5cb-4848-980e-6d6f2dcc2acc</elementGuidId>
    <imagePath></imagePath>
    <name>link_tablesWorkWithSortableTables</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/main[1]/div[1]/div[2]/div[1]/div[1]/a[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}') and equals(@text,'Tables
            
            Work with sortable tables and dynamic data')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>be6fb7c7-aa1f-4e5d-bd60-95064ee6aa41</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Tables
        
        Work with sortable tables and dynamic data</value>
        <webElementGuid>be6fb7c7-aa1f-4e5d-bd60-95064ee6aa41</webElementGuid>
    </webElementProperties>
</WebElementEntity>