<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bcc2e556-4bd5-45f5-83ae-e55ef41efd13</elementGuidId>
    <imagePath></imagePath>
    <name>link_homeCategories</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>${link_homeCategories_css_value_1}</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/nav[1]/ul[1]/li[2]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'js-megaMenu-level-2') and equals(@href,'/product-category/power-management/power-protection-switches-controllers/power-muxes/overview.html') and equals(@text,'Power muxes')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"${link_homeCategories_AInternalText_1}\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>js-megaMenu-level-2</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product-category/power-management/power-protection-switches-controllers/power-muxes/overview.html</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Power muxes</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>