<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d544b14a-0b5e-4510-8d3f-0fa6956ca654</elementGuidId>
    <imagePath></imagePath>
    <name>link_shippingPaymentTaxes</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(3) li:nth-of-type(3) &gt; [class="ti_p-responsiveFooter-link"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/footer[1]/div[1]/div[1]/div[3]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ti_p-responsiveFooter-link') and equals(@href,'//www.ti.com/de-de/ordering-resources/shipping-payment-tax-information.html') and equals(@text,'Versand, Zahlung und Steuern')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Versand, Zahlung und Steuern\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ti_p-responsiveFooter-link</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>//www.ti.com/de-de/ordering-resources/shipping-payment-tax-information.html</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Versand, Zahlung und Steuern</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>