<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cd10faca-7933-4b9b-8850-e387f019b3ed</elementGuidId>
    <imagePath></imagePath>
    <name>span_loginRequired</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ti_p-col-3\ ti_p-col-tablet-4\ ti_p-col-phone-12\ u-hide-only-on-phone"] [class="u-margin-bottom-2\ ti-button-compact\ ti-button-primary\ hydrated"] &gt; span</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/section[1]/div[1]/div[2]/div[1]/div[1]/ti-button[1]/span[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Zum Bestellen bitte anmelden')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.ti_p-col-3 &gt; .ti_ocb-atc &gt; #atc-login-required-TPIC46L02DB &gt; .u-margin-bottom-2 &gt; span</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Zum Bestellen bitte anmelden</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>