<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b8795166-fa2f-4722-b123-5a37d33627bb</elementGuidId>
    <imagePath></imagePath>
    <name>button_chartTypeSelection</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[1]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="edu\.msu\.hr\.hcm\.zhcmturnoverbnalp\:\:sap\.suite\.ui\.generic\.template\.AnalyticalListPage\.view\.AnalyticalListPage\:\:ZHCM_TURNOVER_BN_ALPResults--chart-btnChartType"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'edu.msu.hr.hcm.zhcmturnoverbnalp::sap.suite.ui.generic.template.AnalyticalListPage.view.AnalyticalListPage::ZHCM_TURNOVER_BN_ALPResults--chart-btnChartType') and equals(@title,'Selected Chart Type: Column Chart')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"${button_chartTypeSelection_internalLabel}\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>edu.msu.hr.hcm.zhcmturnoverbnalp::sap.suite.ui.generic.template.AnalyticalListPage.view.AnalyticalListPage::ZHCM_TURNOVER_BN_ALPResults--chart-btnChartType</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Selected Chart Type: Column Chart</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>