<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ae95d8dc-bdb7-4105-affe-e105e0d4ec21</elementGuidId>
    <imagePath></imagePath>
    <name>button_taskActions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/footer[1]/div[1]/div[3]/button[1]"</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'__button10') and equals(@text,'Open Task')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"${button_taskActions_id}\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>__button10</value>
        <webElementGuid>b3b8ec0b-68e9-4362-83d0-50e2cdea7112</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Open Task</value>
        <webElementGuid>b3b8ec0b-68e9-4362-83d0-50e2cdea7112</webElementGuid>
    </webElementProperties>
</WebElementEntity>