<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f8bb3bad-47cd-40f7-ad48-5abd7259f045</elementGuidId>
    <imagePath></imagePath>
    <name>button_draftActions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/footer[1]/div[1]/button[1]"</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Save Draft') and equals(@text,'Save Draft')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"${button_draftActions_internalLabel}\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Save Draft</value>
        <webElementGuid>519f7259-8a78-4d49-9ece-2ee5b98f295e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Save Draft</value>
        <webElementGuid>519f7259-8a78-4d49-9ece-2ee5b98f295e</webElementGuid>
    </webElementProperties>
</WebElementEntity>