<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>eda5ec68-d07c-4bb0-b6ca-fb8984821e7c</elementGuidId>
    <imagePath></imagePath>
    <name>div_sortAndFilterOptions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/section[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[1]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="${div_sortAndFilterOptions_id}"] [class="sapMSLITitleOnly"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"${div_sortAndFilterOptions_id}\"] div &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>