<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>09161122-6e0a-4aa4-854b-75715113d0c1</elementGuidId>
    <imagePath></imagePath>
    <name>div_additionalFilters</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/section[1]/div[1]/ul[1]/li[2]/div[1]/div[1]/div[1]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="${div_additionalFilters_id}"] [class="sapMSLITitleOnly"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"${div_additionalFilters_id}\"] div &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>