<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9dab731e-65e1-4470-a3c0-3abfda37b93a</elementGuidId>
    <imagePath></imagePath>
    <name>item_reportActions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]"</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"${item_reportActions_id}\"] &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>