<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>aceec002-888c-47b5-bec1-e72748b8563f</elementGuidId>
    <imagePath></imagePath>
    <name>link_navigateHome</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[2]/div[3]/div[2]/div[1]/header[1]/div[1]/a[2]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#shell-header-logo</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'shell-header-logo') and equals(@title,'Navigate to Home') and equals(@href,'https://alt5secportal.test.ebsp.msu.edu/sap/bc/ui2/flp#Shell-home')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a[title=\"Navigate to Home\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://alt5secportal.test.ebsp.msu.edu/sap/bc/ui2/flp#Shell-home</value>
        <webElementGuid>519f7259-8a78-4d49-9ece-2ee5b98f295e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>shell-header-logo</value>
        <webElementGuid>519f7259-8a78-4d49-9ece-2ee5b98f295e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Navigate to Home</value>
        <webElementGuid>519f7259-8a78-4d49-9ece-2ee5b98f295e</webElementGuid>
    </webElementProperties>
</WebElementEntity>