<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>62d87613-e992-45c2-b8a4-cce35e905633</elementGuidId>
    <imagePath></imagePath>
    <name>link_hrPayrollInbox</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="${link_hrPayrollInbox_id}"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'__tile408') and equals(@title,'HR/Payroll Inbox
            35') and equals(@href,'https://alt5secportal.test.ebsp.msu.edu/sap/bc/ui2/flp?sap-ushell-config=lean#HRPayrollInbox-update') and equals(@text,'HR/Payroll Inbox
            35')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"${link_hrPayrollInbox_internalLabel}\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://alt5secportal.test.ebsp.msu.edu/sap/bc/ui2/flp?sap-ushell-config=lean#HRPayrollInbox-update</value>
        <webElementGuid>519f7259-8a78-4d49-9ece-2ee5b98f295e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>__tile408</value>
        <webElementGuid>519f7259-8a78-4d49-9ece-2ee5b98f295e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>HR/Payroll Inbox
        35</value>
        <webElementGuid>519f7259-8a78-4d49-9ece-2ee5b98f295e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>HR/Payroll Inbox
        35</value>
        <webElementGuid>519f7259-8a78-4d49-9ece-2ee5b98f295e</webElementGuid>
    </webElementProperties>
</WebElementEntity>