<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>62210d1d-dae5-4981-b8a2-3fe7c31de30d</elementGuidId>
    <imagePath></imagePath>
    <name>link_humanCapitalManagement</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="${link_humanCapitalManagement_id}"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'__tile157') and equals(@title,'Human Capital Management
            Analytics Dashboard') and equals(@href,'https://alt5secportal.test.ebsp.msu.edu/sap/bc/ui2/flp?sap-ushell-config=lean#Hcmanalyticreport-analytics') and equals(@text,'Human Capital Management
            Analytics Dashboard')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Human Capital Management Analytics Dashboard Navigation Tile\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://alt5secportal.test.ebsp.msu.edu/sap/bc/ui2/flp?sap-ushell-config=lean#Hcmanalyticreport-analytics</value>
        <webElementGuid>94a8d97c-0409-4a6a-8ec1-eebdfd8b043d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>__tile157</value>
        <webElementGuid>94a8d97c-0409-4a6a-8ec1-eebdfd8b043d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Human Capital Management
        Analytics Dashboard</value>
        <webElementGuid>94a8d97c-0409-4a6a-8ec1-eebdfd8b043d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Human Capital Management
        Analytics Dashboard</value>
        <webElementGuid>94a8d97c-0409-4a6a-8ec1-eebdfd8b043d</webElementGuid>
    </webElementProperties>
</WebElementEntity>