<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f47dd36e-2117-4fc2-89dc-01e21a778cd5</elementGuidId>
    <imagePath></imagePath>
    <name>span_draftRemoteWorkAgreements</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/section[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[2]/span[1]/span[1]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="${span_draftRemoteWorkAgreements_id}"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"${span_draftRemoteWorkAgreements_id}\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>