<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>90946e24-1a69-4cee-a990-290f9a4591d6</elementGuidId>
    <imagePath></imagePath>
    <name>span_healthRiskIndicators</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/section[2]/section[6]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[2]/div[1]/div[1]/div[6]/div[1]/span[1]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="${span_healthRiskIndicators_id}"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Physical Demands')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#application-AcademicPosition-Fiori-component---detail--selectObj-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-7-application-AcademicPosition-Fiori-component---detail--vboxForm-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-7-5-application-AcademicPosition-Fiori-component---detail--formContainerObj-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-7-application-AcademicPosition-Fiori-component---detail--vboxForm-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-7-5-5-label</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Physical Demands</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>