<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d9f7fba5-f8cc-4ac4-bcb0-9259037105d3</elementGuidId>
    <imagePath></imagePath>
    <name>span_selectOptions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[1]/div[1]/section[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/div[1]/div[1]/div[1]/span[1]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="${span_selectOptions_id}"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"${span_selectOptions_id}\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>