<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4fe64835-f038-4580-907c-a9ea8d9a2296</elementGuidId>
    <imagePath></imagePath>
    <name>span_searchAndPostingDetails</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/section[2]/section[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[6]/div[1]/span[1]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="${span_searchAndPostingDetails_id}"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Is this an Internal only posting?')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#application-AcademicPosition-Fiori-component---detail--selectObj-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-6-application-AcademicPosition-Fiori-component---detail--vboxForm-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-6-0-application-AcademicPosition-Fiori-component---detail--formContainerObj-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-6-application-AcademicPosition-Fiori-component---detail--vboxForm-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-6-0-9-label</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Is this an Internal only posting?</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>