<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9a69375a-f379-4c0b-b4cb-49294d2d7cc6</elementGuidId>
    <imagePath></imagePath>
    <name>span_valueHelpIndicators</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/article[1]/div[1]/div[1]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/span[2]"</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'application-Hcmanalyticreport-analytics-component---mainView--ovpGlobalFilter-filterItemControl_BASIC-orgeh-vhi')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div[title=\"${span_valueHelpIndicators_divTitle}\"] &gt;&gt; internal:label=\"Show Value Help\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>application-Hcmanalyticreport-analytics-component---mainView--ovpGlobalFilter-filterItemControl_BASIC-orgeh-vhi</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>