<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5195501e-c74f-41f2-bf3e-5481875aaca9</elementGuidId>
    <imagePath></imagePath>
    <name>button_addNewRow7</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/section[2]/section[7]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Add New Row')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#application-AcademicPosition-Fiori-component---detail--addRowButtonObj-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-8-application-AcademicPosition-Fiori-component---detail--vboxTable-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-8-2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Add New Row</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>