<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c3e23e50-c6ff-4c6d-8560-900a670d0f09</elementGuidId>
    <imagePath></imagePath>
    <name>button_moreGroups</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[1]/div[1]/div[1]/div[4]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'sapUshellAnchorBarOverflowButton') and equals(@title,'More groups')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"More groups\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>sapUshellAnchorBarOverflowButton</value>
        <webElementGuid>94a8d97c-0409-4a6a-8ec1-eebdfd8b043d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>More groups</value>
        <webElementGuid>94a8d97c-0409-4a6a-8ec1-eebdfd8b043d</webElementGuid>
    </webElementProperties>
</WebElementEntity>