<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b97f72ba-f809-48e7-b733-580d6f676b9a</elementGuidId>
    <imagePath></imagePath>
    <name>button_moreGroups2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[1]/div[1]/div[1]/div[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="sapUshellAnchorBarOverflowButton"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'sapUshellAnchorBarOverflowButton') and equals(@title,'More groups')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"More groups\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>sapUshellAnchorBarOverflowButton</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>More groups</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>