<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bf38fac3-cc00-44e6-83dd-37986310d670</elementGuidId>
    <imagePath></imagePath>
    <name>div_retainedStatus</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>"//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]"</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value></value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'edu.msu.hr.hcm.zhcmretentionbnalp::sap.suite.ui.generic.template.AnalyticalListPage.view.AnalyticalListPage::ZHCM_RETENTION_BN_ALPResults--template::KPITag::KPII::KPI_EETYPE') and equals(@title,'Retained 13,144 
            Status: None')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"RET\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>edu.msu.hr.hcm.zhcmretentionbnalp::sap.suite.ui.generic.template.AnalyticalListPage.view.AnalyticalListPage::ZHCM_RETENTION_BN_ALPResults--template::KPITag::KPII::KPI_EETYPE</value>
        <webElementGuid>b3b8ec0b-68e9-4362-83d0-50e2cdea7112</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Retained 13,144 
        Status: None</value>
        <webElementGuid>b3b8ec0b-68e9-4362-83d0-50e2cdea7112</webElementGuid>
    </webElementProperties>
</WebElementEntity>