<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>33a50041-8d90-4d9f-98f0-3932626a40a2</elementGuidId>
    <imagePath></imagePath>
    <name>div_namePhone</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[5]/td[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"edu\\.msu\\.hr\\.hcm\\.zhcmturnoverbnalp\\:\\:sap\\.suite\\.ui\\.generic\\.template\\.AnalyticalListPage\\.view\\.AnalyticalListPage\\:\\:ZHCM_TURNOVER_BN_ALPResults--analyticalTable-rows-row4-col0\"] div</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>