<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>faa38876-9209-400b-b17d-fbe28d63a1f6</elementGuidId>
    <imagePath></imagePath>
    <name>div_effectiveDate</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/section[1]/div[1]/ul[1]/li[2]/div[1]/div[3]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="__xmlview2--MAIN_LIST_ITEM-__clone1-content"] &gt; [class="sapMObjLBottomRow"] &gt; div:nth-of-type(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.sapMObjLBottomRow &gt; div:nth-child(2) &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>