<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d93b7f3f-f957-40eb-9e0f-bb0c21857c90</elementGuidId>
    <imagePath></imagePath>
    <name>div_employeeDetails8</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'edu.msu.hr.hcm.zhcmturnoverbnalp::sap.suite.ui.generic.template.AnalyticalListPage.view.AnalyticalListPage::ZHCM_TURNOVER_BN_ALPResults--template::ChartToolbar')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Employee Details\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>edu.msu.hr.hcm.zhcmturnoverbnalp::sap.suite.ui.generic.template.AnalyticalListPage.view.AnalyticalListPage::ZHCM_TURNOVER_BN_ALPResults--template::ChartToolbar</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>