<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4e1b956e-0667-431a-af7b-6f068ae70f52</elementGuidId>
    <imagePath></imagePath>
    <name>input_employeeName2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="FilterPanel-filterItemControlA_-edu\.msu\.hr\.hcm\.zhcmretirementbnalp\:\:sap\.suite\.ui\.generic\.template\.AnalyticalListPage\.view\.AnalyticalListPage\:\:ZHCM_RETIRE_AGE_BN_ALPResults--table-ename-inner"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'FilterPanel-filterItemControlA_-edu.msu.hr.hcm.zhcmretirementbnalp::sap.suite.ui.generic.template.AnalyticalListPage.view.AnalyticalListPage::ZHCM_RETIRE_AGE_BN_ALPResults--table-ename-inner') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"\"s &gt;&gt; internal:label=\"Employee Name\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>FilterPanel-filterItemControlA_-edu.msu.hr.hcm.zhcmretirementbnalp::sap.suite.ui.generic.template.AnalyticalListPage.view.AnalyticalListPage::ZHCM_RETIRE_AGE_BN_ALPResults--table-ename-inner</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>