<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3508fb92-6d06-48fc-b17d-0b58abe205e3</elementGuidId>
    <imagePath></imagePath>
    <name>input_job</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[7]/div[1]/div[2]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="edu\.msu\.hr\.hcm\.zhcmreportalp\:\:sap\.suite\.ui\.generic\.template\.AnalyticalListPage\.view\.AnalyticalListPage\:\:ZHCM_DATA_REPORT_ALPResults--template\:\:SmartFilterBar-filterItemControlA_-stell-inner"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'edu.msu.hr.hcm.zhcmreportalp::sap.suite.ui.generic.template.AnalyticalListPage.view.AnalyticalListPage::ZHCM_DATA_REPORT_ALPResults--template::SmartFilterBar-filterItemControlA_-stell-inner') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Expanded header\"s &gt;&gt; internal:label=\"Job\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>edu.msu.hr.hcm.zhcmreportalp::sap.suite.ui.generic.template.AnalyticalListPage.view.AnalyticalListPage::ZHCM_DATA_REPORT_ALPResults--template::SmartFilterBar-filterItemControlA_-stell-inner</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>