<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>90dc6de7-e5f7-4ac0-8334-dd3dd134854c</elementGuidId>
    <imagePath></imagePath>
    <name>input_locationName</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[8]/section[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="application-AcademicPosition-Fiori-component---detail--miBLDG_DESC-inner"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'application-AcademicPosition-Fiori-component---detail--miBLDG_DESC-inner') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Location Name\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>application-AcademicPosition-Fiori-component---detail--miBLDG_DESC-inner</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>