<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0cad620a-f4dc-4a85-ab61-2448924e4727</elementGuidId>
    <imagePath></imagePath>
    <name>link_navigateHome5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[2]/div[1]/header[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#shell-header-logo</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'shell-header-logo') and equals(@title,'Navigate to Home') and equals(@href,'https://alt5secportal.test.ebsp.msu.edu/sap/bc/ui2/flp#Shell-home')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a[title=\"Navigate to Home\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://alt5secportal.test.ebsp.msu.edu/sap/bc/ui2/flp#Shell-home</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>shell-header-logo</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Navigate to Home</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>