<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e91e6abd-7dda-463b-ab5b-3a1fc0eb7a49</elementGuidId>
    <imagePath></imagePath>
    <name>span_showValueHelp10</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/section[2]/section[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="application-AcademicPosition-Fiori-component---detail--inputObj-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-4-application-AcademicPosition-Fiori-component---detail--vboxForm-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-4-0-application-AcademicPosition-Fiori-component---detail--formContainerObj-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-4-application-AcademicPosition-Fiori-component---detail--vboxForm-application-AcademicPosition-Fiori-component---detail--ObjectPageLayout-4-0-0-vhi"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Administrative AddressAdministrative AddressLocation IDLocation IDRoom/Suite #Room/Suite #Phone #(Format {{phone}})Phone #(Format {{phone}})ext.ext.Address Line1Address Line1Address Line2Address Line2CityCityStateStateZip CodeZip CodeCountryCountryShow Less\"s &gt;&gt; internal:label=\"Show Value Help\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>