<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6edfd6a8-e729-487b-b15e-3b267ac14abc</elementGuidId>
    <imagePath></imagePath>
    <name>span_startingFromDateTime</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/section[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/span[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"edu\\.msu\\.hr\\.hcm\\.zhcmretirementbnalp\\:\\:sap\\.suite\\.ui\\.generic\\.template\\.AnalyticalListPage\\.view\\.AnalyticalListPage\\:\\:ZHCM_RETIRE_AGE_BN_ALPResults--template\\:\\:SmartFilterBar-filterItemControlA_-_Parameter\\.recordYear-valueHelpDialog-table-1-control-__clone511\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>