<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>79a4b570-a984-4e0e-a842-819393b30cbb</elementGuidId>
    <imagePath></imagePath>
    <name>span_selectOptions19</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[12]/section[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/div[1]/div[1]/div[1]/span[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Grouped . Row . 3 of 8 . Dimensions . Field Combo Box Personnel subarea . Layout Option Listbox Category . Button Move to Top Disabled Button Move Up Disabled Button Move Down Button Move to Bottom Button Remove\"s &gt;&gt; internal:label=\"Select Options\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>