<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fd384553-35ab-4634-93d3-8908f500d57b</elementGuidId>
    <imagePath></imagePath>
    <name>span_relativesInDepartment</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/div[2]/div[3]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/section[2]/section[4]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[6]/div[1]/span[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="application-GRADProcesses-Fiori-component---detail--selectObj-application-GRADProcesses-Fiori-component---detail--ObjectPageLayout-3-application-GRADProcesses-Fiori-component---detail--vboxForm-application-GRADProcesses-Fiori-component---detail--ObjectPageLayout-3-0-application-GRADProcesses-Fiori-component---detail--formContainerObj-application-GRADProcesses-Fiori-component---detail--ObjectPageLayout-3-application-GRADProcesses-Fiori-component---detail--vboxForm-application-GRADProcesses-Fiori-component---detail--ObjectPageLayout-3-0-0-arrow"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Does the employee have any relatives working in the same department?')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#application-GRADProcesses-Fiori-component---detail--selectObj-application-GRADProcesses-Fiori-component---detail--ObjectPageLayout-3-application-GRADProcesses-Fiori-component---detail--vboxForm-application-GRADProcesses-Fiori-component---detail--ObjectPageLayout-3-0-application-GRADProcesses-Fiori-component---detail--formContainerObj-application-GRADProcesses-Fiori-component---detail--ObjectPageLayout-3-application-GRADProcesses-Fiori-component---detail--vboxForm-application-GRADProcesses-Fiori-component---detail--ObjectPageLayout-3-0-0-arrow</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Does the employee have any relatives working in the same department?</value>
        <webElementGuid>aed727ef-160d-4264-a657-244e7982f4bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>