<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e25a207a-bb37-4105-b042-22e9d19155ef</elementGuidId>
    <imagePath></imagePath>
    <name>span_showValueHelp11</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[22]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="inputTable-formContainerTable-0-vhi"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Area of Interest(select all that apply)Use Arrow keys to move, Shift+Arrow keys to resizeArea of InterestOKOKCancelCancel\"s &gt;&gt; internal:label=\"Show Value Help\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>