<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>58d0ab9c-10e0-4881-9088-33029bac68b4</elementGuidId>
    <imagePath></imagePath>
    <name>span_dateTime2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/section[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/span[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"edu\\.msu\\.hr\\.hcm\\.zhcmreportalp\\:\\:sap\\.suite\\.ui\\.generic\\.template\\.AnalyticalListPage\\.view\\.AnalyticalListPage\\:\\:ZHCM_DATA_REPORT_ALPResults--template\\:\\:SmartFilterBar-filterItemControlA_-_Parameter\\.recordYear-valueHelpDialog-table-0-control-__clone241\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>