<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>730aea98-ae03-4e22-82dd-fbb8b8ad72a5</elementGuidId>
    <imagePath></imagePath>
    <name>td_fiscalYearStart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[5]/section[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[5]/td[2]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"edu\\.msu\\.hr\\.hcm\\.zhcmretirementbnalp\\:\\:sap\\.suite\\.ui\\.generic\\.template\\.AnalyticalListPage\\.view\\.AnalyticalListPage\\:\\:ZHCM_RETIRE_AGE_BN_ALPResults--template\\:\\:SmartFilterBar-filterItemControlA_-_Parameter\\.recordYear-valueHelpDialog-table-rows-row4-col1\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>