<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7c1d2739-b0fa-4235-b628-b26010d91df5</elementGuidId>
    <imagePath></imagePath>
    <name>td_seniorityGroup</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[11]/td[8]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"edu\\.msu\\.hr\\.hcm\\.zhcmretentionbnalp\\:\\:sap\\.suite\\.ui\\.generic\\.template\\.AnalyticalListPage\\.view\\.AnalyticalListPage\\:\\:ZHCM_RETENTION_BN_ALPResults--analyticalTable-rows-row10-col7\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>