<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>07c567f8-aefb-4151-bc93-0c4dcc797524</elementGuidId>
    <imagePath></imagePath>
    <name>link_powerManagement</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(13) &gt; [class="ti_p-megaMenu-nav-action\ js-megaMenu-tab\ js-megaMenu-level-1\ js-hasListeners"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/nav[1]/ul[1]/li[2]/div[1]/div[1]/div[1]/ul[1]/li[13]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ti_p-megaMenu-nav-action js-megaMenu-tab js-megaMenu-level-1 js-hasListeners') and equals(@href,'//www.ti.com/product-category/power-management/overview.html') and equals(@text,'Power management')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text=/^Power management$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ti_p-megaMenu-nav-action js-megaMenu-tab js-megaMenu-level-1 js-hasListeners</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>//www.ti.com/product-category/power-management/overview.html</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Power management</value>
        <webElementGuid>b9394cc7-a80a-4922-998b-d9297a9dd130</webElementGuid>
    </webElementProperties>
</WebElementEntity>