<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e199dc0b-1bdb-4803-bc83-61abfe9b13c3</elementGuidId>
    <imagePath></imagePath>
    <name>link_phoneContact</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/header[1]/nav[1]/div[1]/div[1]/div[2]/a[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}send?phone={{phone}}&amp;text=hello') and equals(@text,'{{phone}}')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"+{{phone}}\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}send?phone={{phone}}&amp;text=hello</value>
        <webElementGuid>3e5675eb-8500-4599-8a08-d942cabe7854</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>{{phone}}</value>
        <webElementGuid>3e5675eb-8500-4599-8a08-d942cabe7854</webElementGuid>
    </webElementProperties>
</WebElementEntity>